/* Do not touch this file! This file is auto generated by build.rs */
#ifndef DCKB_CONST_H
#define DCKB_CONST_H

/* Code hash of DepositLock */
const uint8_t DEPOSIT_LOCK_CODE_HASH[] = {
    174, 22,  126, 152, 102, 18,  143, 100, 137, 210, 145,
    0,   119, 70,  186, 255, 169, 238, 95,  193, 47,  143,
    222, 108, 222, 114, 150, 113, 49,  54,  66,  165};
#endif
