/* Do not touch this file! This file is auto generated by build.rs */
#ifndef DCKB_CONST_H
#define DCKB_CONST_H

/* Code hash of DepositLock */
const uint8_t DEPOSIT_LOCK_CODE_HASH[] = {
    186, 196, 234, 122, 169, 137, 68,  111, 186, 235, 123,
    137, 31,  78,  114, 113, 41,  157, 218, 98,  156, 141,
    223, 220, 87,  101, 196, 126, 249, 24,  105, 136};
#endif
