/* Do not touch this file! This file is auto generated by build.rs */
#ifndef DCKB_CONST_H
#define DCKB_CONST_H

/* Code hash of DepositLock */
const uint8_t DEPOSIT_LOCK_CODE_HASH[] = {144 ,87 ,59 ,126 ,201 ,40 ,127 ,250 ,133 ,29 ,61 ,21 ,39 ,79 ,150 ,157 ,22 ,142 ,1 ,33 ,247 ,120 ,75 ,104 ,237 ,94 ,229 ,152 ,133 ,238 ,130 ,160};
#endif
