/* Do not touch! This file is generated by build.rs */
#ifndef DCKB_CUSTODIAN_LOCK_CODE_HASH_H
#define DCKB_CUSTODIAN_LOCK_CODE_HASH_H
const uint8_t CUSTODIAN_LOCK_CODE_HASH[] = {
    16,  198, 83,  165, 207, 1,   51,  74,  147, 57, 147,
    119, 81,  236, 109, 79,  180, 84,  159, 114, 11, 52,
    86,  235, 197, 140, 145, 167, 109, 77,  118, 218};
#endif