/* Do not touch! This file is generated by build.rs */
#ifndef DCKB_CUSTODIAN_LOCK_CODE_HASH_H
#define DCKB_CUSTODIAN_LOCK_CODE_HASH_H
const uint8_t CUSTODIAN_LOCK_CODE_HASH[] = {24 ,119 ,53 ,10 ,133 ,171 ,35 ,37 ,239 ,75 ,158 ,170 ,191 ,84 ,120 ,37 ,97 ,173 ,106 ,91 ,108 ,210 ,6 ,229 ,122 ,141 ,71 ,139 ,67 ,13 ,129 ,221};
#endif