/* Do not touch! This file is generated by build.rs */
#ifndef DCKB_DAO_LOCK_CODE_HASH_H
#define DCKB_DAO_LOCK_CODE_HASH_H
const uint8_t DAO_LOCK_CODE_HASH[] = {107, 220, 250, 61,  156, 146, 198, 223,
                                      238, 166, 208, 217, 90,  163, 161, 104,
                                      57,  89,  114, 13,  104, 199, 94,  67,
                                      111, 137, 1,   163, 33,  223, 140, 134};
#endif