/* Do not touch! This file is generated by build.rs */
#ifndef DCKB_DAO_LOCK_CODE_HASH_H
#define DCKB_DAO_LOCK_CODE_HASH_H
const uint8_t DAO_LOCK_CODE_HASH[] = {196, 133, 223, 43,  248, 238, 72,  203,
                                      161, 175, 128, 106, 101, 123, 244, 189,
                                      194, 143, 227, 182, 254, 159, 200, 193,
                                      53,  2,   231, 175, 10,  150, 197, 155};
#endif