/* Do not touch! This file is generated by build.rs */
#ifndef DCKB_DAO_LOCK_CODE_HASH_H
#define DCKB_DAO_LOCK_CODE_HASH_H
const uint8_t DAO_LOCK_CODE_HASH[] = {138 ,36 ,177 ,131 ,26 ,163 ,203 ,8 ,113 ,255 ,167 ,233 ,210 ,122 ,164 ,62 ,48 ,36 ,173 ,252 ,230 ,136 ,0 ,226 ,253 ,204 ,81 ,75 ,31 ,222 ,100 ,95};
#endif